package:
  name: occt
  version: 7.2.0

source:
  fn: occ.tar.gz
  url: https://github.com/looooo/occt-feedstock/releases/download/7.2.0/opencascade-7.2.0.tgz
  sha256: 245e344b2cf8a6e0a7d9f45d5d807f8ef48607bcd7a6d763ba2d7b861fa55249

build:
  number: 0
  skip: true                              # [(win and not py35) or osx]

  features:
    - occt7.2.0
    - vc14                                # [win and py35]

  track_features:
    - vc14                                # [win and py35]
    - occt7.2.0

requirements:
  build:
    - python                              # [win]
    - cmake                               # [unix]
    - ninja                               # [win]
    - toolchain                           # [osx]
    - freetype 2.7.*
    - tk 8.5.*
    - freeimage                           # [unix]
    - tbb                                 # [unix]
  run:
    - freetype 2.7.*
    - tk 8.5.*
    - freeimage                           # [unix]
    - tbb                                 # [unix]

test:
  requires:
  - python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
    - which draw.sh                       # [unix]
    - which DRAWEXE                       # [unix]
    - where /r "%PREFIX%" DRAWEXE.exe     # [win]

about:
  home: https://www.opencascade.com/
  license_family: LGPL
  license: LGPL-2.1
  license_file: LICENSE_LGPL_21.txt
  summary: this is the occ (opencascade) CAD-Kernel
  description: Open Cascade Technology (OCCT), formerly called CAS.CADE
               is an open source software development platform for 3D CAD,
               CAM, CAE, etc. that is developed and supported by Open Cascade SAS.
  doc_url: https://www.opencascade.com/content/documentation
  dev_url: http://git.dev.opencascade.org/gitweb/?p=occt.git

extra:
  recipe-maintainers:
    - looooo
