{% set name = "occt" %}
{% set version = "7.9.0" %}
{% set build = 1 %}

{% set build = build + 100 %}   # [variant == "novtk"]
{% set build = build + 200 %}   # [variant == "all"]


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Open-Cascade-SAS/OCCT/archive/refs/tags/V{{ version.replace(".", "_") }}.tar.gz
  sha256: 151b7a522ba8220aed3009e440246abbaf2ffec42672c37e9390096f7f2c098d
  # patches:
  #   # blobfish
  #   - patches/0001-cmake-Don-t-try-to-write-to-install-directory.-You-k.patch
  #   - patches/0002-GeomPlate_BuildAveragePlane-BasePlan-Don-t-set-yvect.patch
  #   - patches/0003-BRepFill_Filling-WireFromList-We-can-t-assume-that-a.patch
  #   - patches/0004-BRepFill_Filling-Curve-constraints-confused-by-impli.patch
  #   - patches/0005-BRepFill_Filling-Don-t-even-attempt-to-build-with-em.patch
  #   - patches/0006-BRepOffset_Tool-TryProject-Check-return-of-BRepLib-B.patch
  #   - patches/0007-ChFi3d_Builder-ChFi3d_ComputeCurves-set-tolreached-f.patch
  #   - patches/0008-BRepLib-MakeEdge-Setting-closed-flag-of-generated-ed.patch
  #   - patches/0009-BRepFill_CompatibleWires-segfault.-See-following.patch
  #   - patches/0010-BRepFill_OffsetWire-segfault.-See-following.patch
  #   - patches/0011-ChFiDS_FilSpine-Allow-usage-of-externally-assigned-l.patch
  #   # disabled due to abi incompatibility
  #   #- patches/0012-Allow-blending-of-faces-less-than-5-degrees.-See-fol.patch
  #   - patches/0013-BRepFill_PipeShell-Fix-segfault-with-line-as-profile.patch
  #   - patches/0015-build-Expand-preprocessor-conditional-on-non-standar.patch
  #   - patches/0016-IntPatch_Intersection-Consider-intersection-of-a-clo.patch
  #   - patches/0017-ChFi3d_Builder-Fix-blend-across-seam.-See-following.patch
  #   # see https://tracker.dev.opencascade.org/view.php?id=33576 and https://github.com/FreeCAD/FreeCAD/issues/9760
  #   - patches/0018-Fix-0033576-BRepTools_NurbsConvertModification-NewPo.patch

build:
  number: {{ build }}
  string: {{ variant }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    # ABI changes between minor versions, see e.g.
    # https://github.com/conda-forge/occt-feedstock/issues/97
    - {{ pin_subpackage('occt', max_pin='x.x.x') }}
  script_env:
    - USE_VTK=OFF  # [variant=='novtk']
    - USE_VTK=ON  # [variant=='all']

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - {{ cdt('libxext-devel') }}    # [linux]
    - {{ cdt('libxi-devel') }}      # [linux]
  host:
    - fontconfig
    - freeimage
    - freetype
    - libgl-devel                   # [linux]
    - rapidjson
    - tbb-devel                     # [win]
    - vtk                           # [variant=='all']
    - xorg-libx11                   # [linux]
    - xorg-libxt                    # [linux]
    - xorg-xorgproto                # [linux]
  run:
    - freetype
    - freeimage
    - fontconfig
    - xorg-libxt  # [linux]
    - rapidjson
    - vtk  # [variant=='all']

test:
  requires:
    - ninja
    - cmake
  files:
    - CMakeLists.txt
  commands:
    - cmake -G "Ninja" .

about:
  home: https://www.opencascade.com/
  license_family: LGPL
  license: LGPL-2.1-only
  license_file: LICENSE_LGPL_21.txt
  summary: this is the occ (opencascade) CAD-Kernel
  description: |
    Open Cascade Technology (OCCT), formerly called CAS.CADE
    is an open source software development platform for 3D CAD,
    CAM, CAE, etc. that is developed and supported by Open Cascade SAS.
  doc_url: https://www.opencascade.com/content/documentation
  dev_url: http://git.dev.opencascade.org/gitweb/?p=occt.git

extra:
  recipe-maintainers:
    - adrianinsaval
    - looooo
