{% set name = "occt" %}
{% set version = "7.5.0.beta" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=V{{ version.replace(".", "_") }};sf=tgz
  sha256: 3b3186c9b1232fa1ded9c53ba836eeab007c3aab397dc27398e63e5547119bbe
  patches:
    - no-xmu.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake 3.18
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
  host:
    - freetype
    - freeimage 
    - fontconfig
    - tbb-devel
    - xorg-libxt  # [linux]
    - vtk
  run:
    - freetype
    - freeimage
    - fontconfig
    - xorg-libxt  # [linux]
    - vtk

test:
  requires:
    - ninja
    - cmake
  files:
    - CMakeLists.txt
  commands:
    - cmake -G "Ninja" .

about:
  home: https://www.opencascade.com/
  license_family: LGPL
  license: LGPL-2.1
  license_file: LICENSE_LGPL_21.txt
  summary: this is the occ (opencascade) CAD-Kernel
  description: |
    Open Cascade Technology (OCCT), formerly called CAS.CADE
    is an open source software development platform for 3D CAD,
    CAM, CAE, etc. that is developed and supported by Open Cascade SAS.
  doc_url: https://www.opencascade.com/content/documentation
  dev_url: http://git.dev.opencascade.org/gitweb/?p=occt.git

extra:
  recipe-maintainers:
    - looooo
