{% set name = "occt-split" %}
{% set version = "7.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=V{{ version.replace(".", "_") }};sf=tgz
  sha256: 9614c2075cef53e30b25317fc8fcfb71d60a69181d562e1c56469ed8e54ad758
  patches:
    - no-xmu.patch
    - fix-private-linking.patch
    - fix-brepblend.patch
    - vtk.patch  # [linux]
    - cmake_policy.patch

build:
  number: 7

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
  host:
    - freetype
    - freeimage 
    - fontconfig
    - tbb-devel
    - xorg-libxt  # [linux]
  run:
    - freetype
    - freeimage
    - fontconfig
    - xorg-libxt  # [linux]


outputs:
  - name: occt-vtk

    script: install_occt_vtk.sh  # [unix]
    script: install_occt_vtk.bat  # [win]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('libxi-devel') }}       # [linux]
        - {{ cdt('libxext-devel') }}     # [linux]
      host:
        - occt
        - vtk
      run:
        - occt
        - vtk

  - name: occt

    script: install_occt.sh  # [unix]
    script: install_occt.bat  # [win]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('libxi-devel') }}       # [linux]
        - {{ cdt('libxext-devel') }}     # [linux]
      host:
        - freetype
        - freeimage 
        - fontconfig
        - tbb-devel
        - xorg-libxt  # [linux]
      run:
        - freetype
        - freeimage
        - fontconfig
        - xorg-libxt  # [linux]

# test:
#   requires:
#     - ninja
#     - cmake
#   files:
#     - CMakeLists.txt
#   commands:
#     - cmake -G "Ninja" .

about:
  home: https://www.opencascade.com/
  license: LGPL-2.1-only WITH OCCT-exception-1.0
  license_file: LICENSE_LGPL_21.txt
  summary: this is the occ (opencascade) CAD-Kernel
  description: |
    Open Cascade Technology (OCCT), formerly called CAS.CADE
    is an open source software development platform for 3D CAD,
    CAM, CAE, etc. that is developed and supported by Open Cascade SAS.
  doc_url: https://www.opencascade.com/content/documentation
  dev_url: http://git.dev.opencascade.org/gitweb/?p=occt.git

extra:
  recipe-maintainers:
    - looooo
