{% set name = "occt" %}
{% set version = "7.7.0" %}

{% if variant == "core" %}
  {% set name = "occt-core" %}
{% endif %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: occt-{{ version }}.tar.gz
  url: http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=V{{ version.replace(".", "_") }};sf=tgz
  sha256: 6845a17fe5f40b3685a571be97e5696605de23cc7abf10f8a644d2163711c6ff
  patches:
    - patches/blobfish.patch

build:
  number: 2
  script_env:
    - USE_VTK=OFF  # [variant=='core']
    - USE_VTK=ON  # [variant=='vtk']

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake 3.18
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
  host:
    - freetype
    - freeimage
    - fontconfig
    - xorg-libxt  # [linux]
    - rapidjson
    - vtk  # [variant=='vtk']
  run:
    - freetype
    - freeimage
    - fontconfig
    - xorg-libxt  # [linux]
    - rapidjson
    - vtk  # [variant=='vtk']

test:
  requires:
    - ninja
    - cmake
  files:
    - CMakeLists.txt
  commands:
    - cmake -G "Ninja" .

about:
  home: https://www.opencascade.com/
  license_family: LGPL
  license: LGPL-2.1-only
  license_file: LICENSE_LGPL_21.txt
  summary: this is the occ (opencascade) CAD-Kernel
  description: |
    Open Cascade Technology (OCCT), formerly called CAS.CADE
    is an open source software development platform for 3D CAD,
    CAM, CAE, etc. that is developed and supported by Open Cascade SAS.
  doc_url: https://www.opencascade.com/content/documentation
  dev_url: http://git.dev.opencascade.org/gitweb/?p=occt.git

extra:
  recipe-maintainers:
    - looooo
