{% set name = "occt" %}
{% set version = "7.8.0" %}
{% set build = 0 %}

{% set build = build + 100 %}   # [variant == "novtk"]
{% set build = build + 200 %}   # [variant == "all"]


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=V{{ version.replace(".", "_") }};sf=tgz
  sha256: e6aee3adc653e667e4881333f088778d8ddc0099d9898972af3b44b0235cd6bb
  patches:
    - patches/blobfish.patch

build:
  number: {{ build }}
  string: {{ variant }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    # ABI changes between minor versions, see e.g.
    # https://github.com/conda-forge/occt-feedstock/issues/97
    - {{ pin_subpackage('occt', max_pin='x.x.x') }}
  script_env:
    - USE_VTK=OFF  # [variant=='novtk']
    - USE_VTK=ON  # [variant=='all']

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake 3.18
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
  host:
    - freetype
    - freeimage
    - fontconfig
    - xorg-libxt  # [linux]
    - rapidjson
    - vtk  # [variant=='all']
  run:
    - freetype
    - freeimage
    - fontconfig
    - xorg-libxt  # [linux]
    - rapidjson
    - vtk  # [variant=='all']

test:
  requires:
    - ninja
    - cmake
  files:
    - CMakeLists.txt
  commands:
    - cmake -G "Ninja" .

about:
  home: https://www.opencascade.com/
  license_family: LGPL
  license: LGPL-2.1-only
  license_file: LICENSE_LGPL_21.txt
  summary: this is the occ (opencascade) CAD-Kernel
  description: |
    Open Cascade Technology (OCCT), formerly called CAS.CADE
    is an open source software development platform for 3D CAD,
    CAM, CAE, etc. that is developed and supported by Open Cascade SAS.
  doc_url: https://www.opencascade.com/content/documentation
  dev_url: http://git.dev.opencascade.org/gitweb/?p=occt.git

extra:
  recipe-maintainers:
    - adrianinsaval
    - looooo
