{% set name = "occt" %}
{% set version = "7.6.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=V{{ version.replace(".", "_") }};sf=tgz
  sha256: 657933e8c2d431345bfaec8934499bcee38e47a24faaf480265f40e85d84c49c
  patches:
    - patches/blobfish.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake 3.18
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
  host:
    - freetype
    - freeimage
    - fontconfig
    - xorg-libxt  # [linux]
    - vtk
    - rapidjson
  run:
    - freetype
    - freeimage
    - fontconfig
    - xorg-libxt  # [linux]
    - vtk
    - rapidjson
test:
  requires:
    - ninja
    - cmake
  files:
    - CMakeLists.txt
  commands:
    - cmake -G "Ninja" .

about:
  home: https://www.opencascade.com/
  license_family: LGPL
  license: LGPL-2.1-only
  license_file: LICENSE_LGPL_21.txt
  summary: this is the occ (opencascade) CAD-Kernel
  description: |
    Open Cascade Technology (OCCT), formerly called CAS.CADE
    is an open source software development platform for 3D CAD,
    CAM, CAE, etc. that is developed and supported by Open Cascade SAS.
  doc_url: https://www.opencascade.com/content/documentation
  dev_url: http://git.dev.opencascade.org/gitweb/?p=occt.git

extra:
  recipe-maintainers:
    - looooo
