context:
  name: occt
  version: '7.9.2'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/Open-Cascade-SAS/OCCT/archive/refs/tags/V${{ version | replace(".", "_") }}.tar.gz
  sha256: 3cd080d3fc33ba0c6c157e110afe3e015859524c4694dbb09812ec9d61595639
  patches:
    - patches/switch-vtk-freetype-cmake-order.patch

build:
  variant:
    down_prioritize_variant: ${{ 0 if variant == 'all' else 1 }}
  number: 1
  string: ${{ variant }}_h${{ PKG_HASH }}_${{ build }}
  script:
    file: build${{ '.sh' if unix else '.bat' }}
    env:
      USE_VTK: ${{ 'ON' if variant == 'all' else 'OFF' }}

requirements:
  run_exports:
    # ABI changes between minor versions, see e.g.
    # https://github.com/conda-forge/occt-feedstock/issues/97
    - ${{ pin_subpackage('occt', upper_bound='x.x.x', lower_bound='x.x.x') }}
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - if: linux
      then:
        - ${{ cdt('libxext-devel') }}
        - ${{ cdt('libxi-devel') }}
  host:
    - fontconfig
    - freeimage
    - freetype
    - if: linux
      then:
        - libgl-devel
        - xorg-libx11
        - xorg-libxt
        - xorg-xorgproto
    - rapidjson
    - if: variant == 'all'
      then:
        - tbb-devel
        - vtk
  run:
    - freetype
    - freeimage
    - fontconfig
    - if: linux
      then:
        - xorg-libxt
    - rapidjson
    - if: variant == 'all'
      then:
        - vtk

tests:
  - requirements:
      run:
        - ninja
        - cmake
    files:
      recipe:
        - CMakeLists.txt
    script:
      - cmake -G "Ninja" .

about:
  homepage: https://www.opencascade.com/
  license: LGPL-2.1-only
  license_file: LICENSE_LGPL_21.txt
  summary: this is the occ (opencascade) CAD-Kernel
  description: |
    Open Cascade Technology (OCCT), formerly called CAS.CADE
    is an open source software development platform for 3D CAD,
    CAM, CAE, etc. that is developed and supported by Open Cascade SAS.
  documentation: https://www.opencascade.com/content/documentation
  repository: http://git.dev.opencascade.org/gitweb/?p=occt.git

extra:
  recipe-maintainers:
    - adam-urbanczyk
    - oursland
    - adrianinsaval
    - looooo
