azure:
  settings_win:
    variables: {CONDA_BLD_PATH: C:\bld\}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
build_platform: {osx_arm64: osx_64}
