appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {osx: circle}
travis:
  secure: {BINSTAR_TOKEN: JZjO433are1fYYgAGIhBtEG1CaoOEFF5oLnYSGe5DonEbVxpMfSG0KCvZVz4Af0fPSOyn3gnM0fNe2+GOliD7nUaXdP9gh2g0+2sDIxW0Velp9bfhRgT02dFQS+1n7OXWqkyN/aMnW3mu/XCax6NVU8K7v3CUTaKjMUP/DgncM0gJf7IQoOYvCsNqQ2w5SRLXdloORSn42I1CxlQG5YReXBueZMqijZzhy4Is5Zsznu7Bvf86gRVHPDI9rdeFyPa5YBmhn80MatdhKQnHpzh3xTC4hI0mNZdLWu2ZSp9PpfYTy8lZCEKLR/Yd+MJowjWcEQqutvPDl3ddJWN13HMIMZsD4aYloAnXKtxp9zaUHpGKaZBA67k2HnhOcSulxnEkc76fcgiCPG86SWn1RN/8uPy8BP30R2YzVl74v/OoKuqtfCN4OFUkRttfWnmQ5iNLN2TouuU+dqejI1iMmOG9QNNn+6/GvFafS8Pft6fFHk/QEf5t8JsGq0I/1PI5Cri8wStu4o0D27H4cTiaRWMQkAC18SrGEsbNDQV6eYCQzkKIs6uRJ3XOqTwsIpfal3kH696ECcFE4nxCgjjYgOkGp4bIRxK+xpazqOTbVqAfIujwNy9E1AgHFG6RSk7XcThjsuADAp8RwLArIR6knR7lr/MvZpKN7ANLCVECeZygH4=}
