travis:
  secure:
    BINSTAR_TOKEN: BVyJFINLAzac4nuOQwZSaD/0elNCqBzbU46olyu77c/5vnSyqC1qR2jd+M9Pdf1HSXu9XUKVQgd0SkfaZVnIFasgR3JhslBEgs9/1PKUw2orQI3P3fqtNX8Ly/86VaUHt2xAAfcthAdgHXxIfFxIbnBcq7XfsvyIXYWNEMHbRWMyq2NobcXP6FsmXW6+QJXFn3d97LFyrfF/SVZxrk0JVDoPkhWm757XzztluZGI7U5xZSeiSl2bFb0mLTbY146Mj2oifQGKrK0VQIryDW9Qt6wx8njpDbHhaEwpo5RUYzXcsGFSGlL4OppbexQQlbjcv6a6lqYPC6kUjSesiYnCKz+XhOdCIQ2wtaN2mrEglumCFOFoBGEglx/V9dOSJQuVIHhMKXvsRp1hgJvv4Uap7ZAF1Z6Xl8QG8OyHbkAftMN7I6o82N+7DFJHCO/fjrLUdT+zqq3JZ8dFZI9KzjyKrGRuqn0Ezo7jCpauDi/8y1gRjQb6i8wUzIjR/G98Bw86pFgJ3aT9OX2hXxH/AbwSlSxDHcPWoccmpionF8hXfiIzcJBA0ZavVLk1GcaDD1JSjHhYXxj/NBlCCNBuY6FXu5L3KuhQy9WlyZvZmkovlVqJRy0kUGi+q4EOWNvqYb1Lo6lwabgQzX5fdBv4J8VDRRf60s3nJBk/+BkwoQADZNo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
