version: 2

jobs:
  build_circle_:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "circle_"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh

  build_travis_:
    working_directory: ~/test
    macos:
      xcode: "9.0"
    environment:
      - CONFIG: "travis"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_osx_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_travis_
      - build_circle_
